### PR TITLE
Use exceptions instead of ErrorStatus

### LINKED ISSUE #11: Methods should throw exceptions rather than using the ErrorStatus enums
Currently, since the bindings are "down to the metal", many of the APIs accept an `ErrorStatus` that must be checked. To better fall in line with Java conventions, like the Python bindings, these `ErrorStatus` objects should not be exposed to users. Instead they should be checked internally and rewrapped as exceptions.

Here is an example of current usage:

```Java
ErrorStatus err = new ErrorStatus();
final String firstImageUrl = outImages.getTargetURLForImageNumber(0, err);
if (err.getOutcome() != ErrorStatus.Outcome.OK) {
    ... do some error handling
}
```

Ideally, this would look something more like:

```Java
try {
    final String firstImageUrl = outImages.getTargetURLForImageNumber(0);
catch (IndexOutOfBoundsException error) {
    ... do some error handling
}
```

The Python ErrorStatus to Exception mappers are good reference.

-  OpenTimelineIO `ErrorStatus` mapper is [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/64d7240266378753c2651f12e65a27812fc58e55/src/py-opentimelineio/opentimelineio-bindings/otio_errorStatusHandler.cpp#L32-L64)
- OpenTime `ErrorStatus` Mapper is [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/64d7240266378753c2651f12e65a27812fc58e55/src/py-opentimelineio/opentime-bindings/opentime_rationalTime.cpp#L21).

Also, of note, the Java `ErrorStatus` [bindings only expose ](https://github.com/OpenTimelineIO/OpenTimelineIO-Java-Bindings/blob/607c610771f02736872153278ceebe5a8fe10664/src/main/java/io/opentimeline/opentimelineio/ErrorStatus.java#L62)`outcome`, they fail to include the [other helpful fields](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/64d7240266378753c2651f12e65a27812fc58e55/src/opentimelineio/errorStatus.h#L68-L71).

### PR DESCRIPTION
**Pull request by KarthikRIyer**
I've just converted opentime ErrorStatus right now. Will work on opentimelineio subsequently.
I haven't deleted `io.opentime.ErrorStatus` yet because it might be used in opentimelineio tests. Once all conversions are done, I'll get rid of ErrorStatus entirely.

Resolves #11

### CODE REVIEW

File: src/main/cpp/exceptions.cpp [hunk 1]
```diff
@@ -0,0 +1,135 @@
+#include "exceptions.h"
+#include "utilities.h"
+
+jint processOpenTimeErrorStatus(JNIEnv *env, opentime::ErrorStatus &errorStatus) {
+    std::string otio_msg = "An OpenTime call failed with ";
```
Comment (reinecke) [inline src/main/cpp/exceptions.cpp:5]: Do we need the text "An OpenTime call failed with" at the beginning of the error message? Will the traceback make it clear that it came from an OpenTime call? If there are ways the context can be lost in the traceback (because of some JNI stuff), then maybe it's best to keep it. But if it's redundant we should address it.

File: src/main/cpp/exceptions.cpp [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+        case opentime::ErrorStatus::Outcome::NEGATIVE_VALUE: {
+            const char *className = "java/lang/IllegalArgumentException";
+            jclass exClass = env->FindClass(className);
+            otio_msg = otio_msg + opentime::ErrorStatus::outcome_to_string(errorStatus.outcome);
+            return env->ThrowNew(exClass, otio_msg.c_str());
+        }
+        case opentime::ErrorStatus::Outcome::OK:
+            return 0;
+        default: {
+            const char *className = "java/lang/Exception";
```
Comment (reinecke) [inline src/main/cpp/exceptions.cpp:22]: Perhaps we should throw a base `OpenTimeException` here instead (this would be a direct subclass of `Exception`)?

File: src/main/cpp/exceptions.cpp [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+    std::string otio_msg = "An OpenTime call failed with ";
+    switch (errorStatus.outcome) {
+        case opentime::ErrorStatus::Outcome::INVALID_TIMECODE_RATE:
+        case opentime::ErrorStatus::Outcome::INVALID_TIMECODE_STRING:
+        case opentime::ErrorStatus::Outcome::INVALID_TIME_STRING:
+        case opentime::ErrorStatus::Outcome::INVALID_RATE_FOR_DROP_FRAME_TIMECODE:
+        case opentime::ErrorStatus::Outcome::NON_DROPFRAME_RATE:
+        case opentime::ErrorStatus::Outcome::TIMECODE_RATE_MISMATCH:
+        case opentime::ErrorStatus::Outcome::NEGATIVE_VALUE: {
+            const char *className = "java/lang/IllegalArgumentException";
```
Comment (reinecke) [inline src/main/cpp/exceptions.cpp:14]: Now that I look at these, `IllegalArgumentException` is unchecked which means consumers of the API aren't forced to handle it. Looking at [this Stack Overflow answer](https://stackoverflow.com/questions/15208544/when-should-an-illegalargumentexception-be-thrown), I agree with the author that is should be used for more obvious programmer error kinds of things.
Since these errors are related to "business logic" about time and can be caused by specific combinations of seemingly valid values (nonnull for example), perhaps we should throw something like an `OpenTimeException`.
Additionally, maybe we want to make specific `OpenTimeException` subclasses for some of these cases. This would allow users to differentiate between and better handle the specific error given their business domain.

File: src/main/cpp/exceptions.cpp [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+        }
+        case OTIO_NS::ErrorStatus::Outcome::FILE_OPEN_FAILED:
+        case OTIO_NS::ErrorStatus::Outcome::FILE_WRITE_FAILED: {
+            const char *className = "java/io/IOException";
+            jclass exClass = env->FindClass(className);
+            otio_msg = otio_msg + errorStatus.full_description;
+            return env->ThrowNew(exClass, otio_msg.c_str());
+        }
+        case OTIO_NS::ErrorStatus::Outcome::INTERNAL_ERROR:
+        case OTIO_NS::ErrorStatus::Outcome::KEY_NOT_FOUND: {
```
Comment (reinecke) [inline src/main/cpp/exceptions.cpp:53]: For `KEY_NOT_FOUND`, do you happen to know the cases where this comes up? I suspect users may want to explicitly catch and handle some of these cases.
If this is used in mapping-like objects, we may want to consider implementing the [Mapping interface](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html) instead (this would mean returning `null`).
If implementing the Mapping interface is the right answer, I think that would be out of scope for this PR. In that case I would suggest maybe we use `IndexOutOfBoundsException` for now and file a separate ticket to address this.

File: src/main/java/io/opentimeline/opentimelineio/exception/CannotComputeAvailableRangeException.java [hunk 5]
```diff
@@ -0,0 +1,10 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright Contributors to the OpenTimelineIO Project.
+
+package io.opentimeline.opentimelineio.exception;
+
+public class CannotComputeAvailableRangeException extends OpenTimelineIOException {
+    public CannotComputeAvailableRangeException(String message) {
+        super("An OpenTimelineIO call failed with: " + message);
```
Comment (reinecke) [inline src/main/java/io/opentimeline/opentimelineio/exception/CannotComputeAvailableRangeException.java:8]: I'd suggest moving this logic into where the exception is thrown. This implicit behavior could be unpredictable to consumers of the class.

**Review by reinecke — CHANGES_REQUESTED** [review]
Looking really nice! The unittest examples show how much cleaner this is to use too!
One thing I'd like to avoid doing is ever raising just plain `Exception`, we should treat `OpenTimeException` and `OpenTimelineIOException` as the fail-safe exceptions.

Other than that, some small things, but I can't wait to start using it!

File: .github/workflows/gradle.yml [hunk 6]
```diff
@@ -29,7 +29,7 @@ jobs:
         java-version: 1.8
     - name: Build with Gradle
       shell: bash
-      run: ./gradlew build
+      run: ./gradlew build -i
```
[the remark this answers is not in the document]
Comment (KarthikRIyer) [reply .github/workflows/gradle.yml:32]: I was on Linux n wanted to see if the verbose output gave any info about why the test failed in Windows. But it didn't.

File: src/main/cpp/exceptions.cpp [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+        case opentime::ErrorStatus::Outcome::INVALID_TIMECODE_STRING:
+        case opentime::ErrorStatus::Outcome::INVALID_TIME_STRING:
+        case opentime::ErrorStatus::Outcome::INVALID_RATE_FOR_DROP_FRAME_TIMECODE:
+        case opentime::ErrorStatus::Outcome::NON_DROPFRAME_RATE:
+        case opentime::ErrorStatus::Outcome::TIMECODE_RATE_MISMATCH:
+        case opentime::ErrorStatus::Outcome::NEGATIVE_VALUE: {
+            const char *className = "java/lang/IllegalArgumentException";
+            jclass exClass = env->FindClass(className);
+            otio_msg = otio_msg + opentime::ErrorStatus::outcome_to_string(errorStatus.outcome);
+            return env->ThrowNew(exClass, otio_msg.c_str());
```
[the remark this answers is not in the document]
Comment (KarthikRIyer) [reply src/main/cpp/exceptions.cpp:17]: Yes. That's a good idea. I'll do that.

File: src/main/cpp/exceptions.cpp (hunk 1 above)
Comment (KarthikRIyer) [reply src/main/cpp/exceptions.cpp:5]: Ohh yeah. Forgot about the traceback 😅
I'll remove this extra text.

File: src/main/cpp/exceptions.cpp (hunk 4 above)
Comment (KarthikRIyer) [reply src/main/cpp/exceptions.cpp:53]: It's present only in the deserialize function but I didn't understand when it would come up.

File: .github/workflows/gradle.yml (hunk 6 above)
[the remark this answers is not in the document]
Comment (reinecke) [reply .github/workflows/gradle.yml:32]: Would it make sense to restore it back, since it was just there for debugging?

File: src/main/cpp/exceptions.cpp (hunk 4 above)
Comment (reinecke) [reply src/main/cpp/exceptions.cpp:59]: It looks like it pops up in the `SerializableObject::Reader::read` family of functions - it's used when schema implementations are deserializing their fields.
For example, here is some usage in ImageSequenceReference: https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/27adbc3c5f62aec8a2cd47b990a7f0507f48a9f2/src/opentimelineio/imageSequenceReference.cpp#L129-L135

So, maybe this should be something like a `SerializationException`?

**Review by reinecke — APPROVED** [review]
Two very small comments. I think this is in a really great state - let me know how/if you want to address the two notes I left. Otherwise, I'm happy with it!

File: src/main/cpp/exceptions.cpp (hunk 4 above)
Comment (KarthikRIyer) [reply src/main/cpp/exceptions.cpp:59]: Shouldn't it be DeserializationException?

File: .github/workflows/gradle.yml (hunk 6 above)
[the remark this answers is not in the document]
Comment (KarthikRIyer) [reply .github/workflows/gradle.yml:32]: If it doesn't make a lot of difference, can we let this be? It might give some extra infowhen something breaks. For example, the expected and current value in an assertion when an assertion fails.

File: src/main/cpp/exceptions.cpp (hunk 4 above)
Comment (reinecke) [reply src/main/cpp/exceptions.cpp:59]: Haha, yes :)

File: .github/workflows/gradle.yml (hunk 6 above)
[the remark this answers is not in the document]
Comment (reinecke) [reply .github/workflows/gradle.yml:32]: I just like to avoid over-chatty logs where possible, it can sometime make it harder to find important info.  But if this is providing value, then it's totally fine.

**Comment by KarthikRIyer** [comment]
Done!

**Review by reinecke — APPROVED** [review]
